### ISSUE TITLE
initialBindings in combination with named graph

### ISSUE THREAD

**Issue by ddeboer** [comunica/comunica#1154]
#### Issue type:

- :bug: Bug 

____
#### Description:

This query works fine:

```sparql
CONSTRUCT FROM <http://www.ontotext.com/retain-bind-position> WHERE { ?s ?p ?o }  LIMIT 100
```

With code:

```js
const quadStream = await this.engine.queryQuads(query, {
  sources: [
        {
          type: 'sparql',
          value: 'https://www.goudatijdmachine.nl/sparql/repositories/gtm',
        },
      ],
});
```

But when adding initial bindings, we get an error:

```js
const quadStream = await this.engine.queryQuads(query, {
  sources: [
        {
          type: 'sparql',
          value: 'https://www.goudatijdmachine.nl/sparql/repositories/gtm',
        },
      ],
  initialBindings: bindingsFactory.fromRecord({}) as unknown as Bindings,
});
```

Conversely, when we’re not querying named graphs, the initial bindings work fine:

```sparql
CONSTRUCT WHERE { ?s ?p ?o } LIMIT 100
```
____
#### Environment:

@comunica/query-sparql@2.6.6

#### Crash log:

```
Cannot read properties of undefined (reading '0')","stack":"TypeError: Cannot read properties of undefined (reading '0')\n    at translateFrom (/Users/david/src/netwerk-digitaal-erfgoed/network-of-terms/node_modules/sparqlalgebrajs/lib/sparql.js:228:32)\n    at translateOperation (/Users/david/src/netwerk-digitaal-erfgoed/network-of-terms/node_modules/sparqlalgebrajs/lib/sparql.js:71:33)\n    at translateProject (/Users/david/src/netwerk-digitaal-erfgoed/network-of-terms/node_modules/sparqlalgebrajs/lib/sparql.js:369:41)\n    at translateOperation (/Users/david/src/netwerk-digitaal-erfgoed/network-of-terms/node_modules/sparqlalgebrajs/lib/sparql.js:82:36)\n    at toSparqlJs (/Users/david/src/netwerk-digitaal-erfgoed/network-of-terms/node_modules/sparqlalgebrajs/lib/sparql.js:48:18)\n    at toSparql (/Users/david/src/netwerk-digitaal-erfgoed/network-of-terms/node_modules/sparqlalgebrajs/lib/sparql.js:42:32)\n    at ActorQueryOperationSparqlEndpoint.run (/Users/david/src/netwerk-digitaal-erfgoed/network-of-terms/node_modules/@comunica/actor-query-operation-sparql-endpoint/lib/ActorQueryOperationSparqlEndpoint.js:75:52)\n    at ActorQueryOperationSparqlEndpoint.runObservable (/Users/david/src/netwerk-digitaal-erfgoed/network-of-terms/node_modules/@comunica/core/lib/Actor.js:57:29)\n    at MediatorNumber.mediate (/Users/david/src/netwerk-digitaal-erfgoed/network-of-terms/node_modules/@comunica/core/lib/Mediator.js:79:22)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","path":["terms"],"locations":[{"line":2,"column":3}],"extensions":{}},"message":"Cannot read properties of undefined (reading '0')"}
```

**Comment by rubensworks** [comment]
A bounty has been placed on this issue via the Comunica Association (see original post).

I suspect this is just a small issue in https://github.com/joachimvh/SPARQLAlgebra.js related to this call: https://github.com/comunica/comunica/blob/master/packages/bus-query-operation/lib/Bindings.ts#L41

**Comment by simonvbrae** [comment]
This issue has been fixed in the following commit:
https://github.com/joachimvh/SPARQLAlgebra.js/commit/edfbb300a32cb7c2314e7a58718457cef8231a7e

**Comment by rubensworks** [comment]
We'll bump the sparqlalgebra version in a next version of comunica.
