### ISSUE TITLE
Clearer error reporting for incorrect input

### ISSUE THREAD

**Issue by RubenVerborgh** [comunica/comunica#119]
_This issue has been modified by @rubensworks to describe the intended solution_

**Problem:**

The problem is that some (most?) errors that can be produced by Comunica are quite cryptic.
This is a consequence of inter-actor communication happening via mediators, which can produce errors such as:
```
Error: https://.../rdf-dereference.json#mediatorRdfParse mediated over all rejecting actors:
Error: Unrecognized media type: text/html
Error: Unrecognized media type: text/html
Error: Unrecognized media type: text/html
    at MediatorRace.js:55
```

So the common format is that mediators show an error message that accumulates error messages from failing actors.

**Possible solution:**

One possible solution could be to reformat these types of error messages to something roughly like:
```
Error: RDF parsing failed: none of the configured parsers were able to handle the content type 'text/html'.
  Error messages of failing actors:
    ActorNameX: Unrecognized media type: text/html
    ActorNameY: Unrecognized media type: text/html
    ActorNameZ: Unrecognized media type: text/html
```

(certainly open to other suggestions)

**Implementation suggestions:**

We could have mediators accept an error message format (with placeholders for things such as `contentType` in parsing actions).

Each mediator would also require some polishing (and alignment) in how it produces error messages.

Something like the following should be possible: `mediator.mediate(action, (failReasons) => 'This is an error message')`

-----

Original issue:

#### Issue type:

- :heavy_plus_sign: Feature request

#### Description:

When invoking `comunica-sparql` with (for instance) an error in the query, I get:

```
Error: Unknown prefix: schema
    at Object.anonymous (/Users/ruben/.nvm/versions/node/v8.9.4/lib/node_modules/@comunica/actor-init-sparql/node_modules/sparqljs/lib/SparqlParser.js:498:29)
    at Parser.parse (/Users/ruben/.nvm/versions/node/v8.9.4/lib/node_modules/@comunica/actor-init-sparql/node_modules/sparqljs/lib/SparqlParser.js:642:36)
    at Parser.parser.parse (/Users/ruben/.nvm/versions/node/v8.9.4/lib/node_modules/@comunica/actor-init-sparql/node_modules/sparqljs/sparql.js:22:37)
    at Object.translate (/Users/ruben/.nvm/versions/node/v8.9.4/lib/node_modules/@comunica/actor-init-sparql/node_modules/sparqlalgebrajs/lib/sparqlAlgebra.js:30:25)
    at ActorSparqlParseAlgebra.run (/Users/ruben/.nvm/versions/node/v8.9.4/lib/node_modules/@comunica/actor-init-sparql/node_modules/@comunica/actor-sparql-parse-algebra/lib/ActorSparqlParseAlgebra.js:16:47)
    at MediatorRace.mediate (/Users/ruben/.nvm/versions/node/v8.9.4/lib/node_modules/@comunica/actor-init-sparql/node_modules/@comunica/core/lib/Mediator.js:80:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:686:11)
    at startup (bootstrap_node.js:187:16)
```

Would be helpful to a) hide the stacktrace (only show it when a certain flag is set) and b) for this particular case, make the error message (a bit) more descriptive.

-----

## Bounty

A [bounty](https://comunica.dev/association/bounties/) has been placed on this issue by:

| |
|-|
| [<img alt="Comunica Association" src="https://comunica.dev/img/comunica_red.svg" height="50">](https://comunica.dev/association/) |
| €1632 |

[Click here to learn more](https://comunica.dev/association/bounty_process/) if you're interested in claiming this bounty by resolving this issue.

**Comment by rubensworks** [comment]
Another example of a very unclear error:
```
Error: https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql/^1.0.0/config/sets/rdf-dereference.json#mediatorRdfParse mediated over all rejecting actors:
Error: Unrecognized media type: text/html
Error: Unrecognized media type: text/html
Error: Unrecognized media type: text/html
    at MediatorRace.js:55
```

**Comment by rubensworks** [comment]
Related to #164.

**Comment by rubensworks** [comment]
As mentioned in https://github.com/solid/community-server/pull/760#discussion_r645617536, we may also want to add a CLI flag (such as `showStackTrace`) to only print full stacktraces iff this flag is present.

**Comment by rubensworks** [comment]
This has been implemented for inclusion in v4.
