### ISSUE TITLE
`HttpServiceSparqlEndpoint` does not support void queries

### ISSUE THREAD

**Issue by jeswr** [comunica/comunica#1219]
#### Issue type:

- :bug: Bug 

____
#### Description:

When trying to execute an insert or delete query over a sparql server started using `HttpServiceSparqlEndpoint` a 400 error code is returned.

This can be reproduced by running the following script, which gives the error at the bottom of this issue.

```ts
import { HttpServiceSparqlEndpoint } from '@comunica/actor-init-query';
import { QueryEngine } from '@comunica/query-sparql-file';
import path from 'path';

async function main() {
  const service = new HttpServiceSparqlEndpoint({
    defaultConfigPath: path.join(__dirname, 'node_modules', '@comunica', 'query-sparql-file', 'config', 'config-default.json'),
    moduleRootPath: __dirname,
    context: {
      sources: [path.join(__dirname, 'data.ttl')]
    }
  });

  await service.run(process.stdout, process.stderr);

  // Give the service time to start up
  await new Promise(resolve => setTimeout(resolve, 5000))

  try {
    const engine = new QueryEngine();
    await engine.queryVoid(`
    PREFIX : <http://example.org/>

    INSERT DATA {
      :s :p :o .
    }`, {
    sources: [
      'http://localhost:3000/sparql'
    ]
  })
  } catch (e) {
    console.log('\n\n', '-'.repeat(10))
    console.error("CLIENT ERRROR:", e);
    console.log('-'.repeat(10), '\n\n');
    process.exit();
  };
}

main();
```

____
#### Environment:

```
{
  "name": "",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start:sparql": "ts-node sparql.ts",
    "start:css": "community-solid-server"
  },
  "keywords": [],
  "author": "",
  "license": "MIT",
  "dependencies": {
    "@comunica/actor-init-query": "^2.7.1",
    "@comunica/query-sparql-file": "^2.7.1",
    "@solid/community-server": "^6.0.0"
  },
  "devDependencies": {
    "ts-node": "^10.9.1"
  }
}

```
#### Crash log:

```
> css-sparql-example@1.0.0 start:sparql
> ts-node sparql.ts

Server running on http://localhost:3000/sparql
Server worker (623267) running on http://localhost:3000/sparql
[200] POST to /sparql
      Requested media type: null
      Received void query: 
    PREFIX : <http://example.org/>

    INSERT DATA {
      :s :p :o .
    }
Worker 623267 got assigned a new query (0).
[400] Bad request


 ----------
CLIENT ERRROR: Error: Invalid SPARQL endpoint response from http://localhost:3000/sparql (HTTP status 400):
empty response
    at SparqlEndpointFetcher.handleFetchCall (/home/jeswr/Documents/GitHub/n2/css-sparql-example/node_modules/fetch-sparql-endpoint/lib/SparqlEndpointFetcher.ts:247:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SparqlEndpointFetcher.fetchUpdate (/home/jeswr/Documents/GitHub/n2/css-sparql-example/node_modules/fetch-sparql-endpoint/lib/SparqlEndpointFetcher.ts:166:5)
    at async main (/home/jeswr/Documents/GitHub/n2/css-sparql-example/sparql.ts:21:5)
---------- 
```

**Comment by rubensworks** [comment]
You have to set `KeysQueryOperation.readOnly` to `false` in your context. By default, endpoints are in read-only mode, for security reasons. (there's also a CLI option for it)
