### ISSUE TITLE
CONSTRUCT quad query causes "Query result type 'quads' was expected, while 'bindings' was found"

### ISSUE THREAD

**Issue by sparkling** [comunica/comunica#1249]
#### Issue type:

- :bug: Bug 

____
#### Description:
This code:

```
import { QueryEngine } from '@comunica/query-sparql';
const myEngine = new QueryEngine();

const sources = [{
  'type': 'sparql', 
  value: 'http://localhost:12110/datastores/df/sparql'
}];

const quadStream = await myEngine.queryQuads(`
const quadStream = await myEngine.queryQuads(`
  PREFIX df: <http://ns.client.com/>
  CONSTRUCT {
      ?item df:hasChild ?child .
      ?child rdfs:label ?childLabel .
      ?child df:hasOrder ?order .
      ?child df:isLeaf ?isLeaf .
      ?child df:hasProductCategory ?productCategory .
  } WHERE {
    BIND (df:ProductCategoryHierarchyItem\/107 as ?item) . 
    ?childVersion rdfs:subClassOf ?item .
    ?childVersion df:isVersionOfProductCategoryHierarchyItem ?child .
    ?child rdfs:label ?childLabel .
    ?child df:hasLatestVersion ?childVersion .
    ?childVersion df:isDeleted false .
    ?childVersion df:isPublished true .
    BIND ( EXISTS {?childVersion df:mirrorsProductCategory ?productCategory} as ?isLeaf) .
    OPTIONAL {
    ?childVersion df:mirrorsProductCategory ?productCategory .
    }
    OPTIONAL { ?childVersion df:hasOrder ?order }
  } `, {
  sources: ['http://localhost:12110/datastores/df/sparql'],
});`,
{sources});

const quads = await quadStream.toArray();
```

Throws this error:
```
Error: Query result type 'quads' was expected, while 'bindings' was found.
    at QueryEngine.queryOfType (/Users/henrik/source/arcablanca/communica/node_modules/@comunica/actor-init-query/lib/QueryEngineBase.js:33:15)
    at async runIt (file:///Users/henrik/source/arcablanca/communica/query.js:13:22)
```
and nothing is ever sent to the server.
____
#### Environment:

```
  "dependencies": {
    "@comunica/query-sparql": "^2.8.1",
    "graphql-to-sparql": "^3.0.1"
  }
```

**Comment by sparkling** [comment]
No, but you can put any URL in there, it never gets so far as to actually send anything. 

However, turns out the weird behaviour was caused by a missing prefix mapping:
```
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
```

Probably a good idea to look at how parse exceptions are handled.

Thanks for the help!
