### ISSUE TITLE
@comunica/query-sparql raises 'Unknown entity type: update' on graphDB SPARQL Update queries.

### ISSUE THREAD

**Issue by Comkiled** [comunica/comunica#1274]
#### Issue type:

- :bug: Bug 

____
#### Description:

I am using the queryEngine.queryVoid() method for an INSERT DATA query on a graphDB instance. My insert query can be simplified to the following, while still resulting in the Error:

```
const query = `insert data {
        <http://example.org/scr#scr> rdf:type owl:Class.
 }`
```
The call looks like this:
```
await this.queryEngine.queryVoid(
query,
{ sources:[{ type: 'sparql', value: source }],
  httpAuth: `${initData.dbCredentials.user}:${initData.dbCredentials.password}`
})
```
The error states:
```
Error: Unknown entry type: update
    at Generator.toPattern (C:\Users\User\Documents\ontology-source-connector\node_modules\sparqljs\lib\SparqlGenerator.js:97:11)
    at Array.map (<anonymous>)
    at mapJoin (C:\Users\User\Documents\ontology-source-connector\node_modules\sparqljs\lib\SparqlGenerator.js:440:16)
    at Generator.array (C:\Users\User\Documents\ontology-source-connector\node_modules\sparqljs\lib\SparqlGenerator.js:106:10)
    at Generator.toPattern (C:\Users\User\Documents\ontology-source-connector\node_modules\sparqljs\lib\SparqlGenerator.js:98:20)
    at Generator.group (C:\Users\User\Documents\ontology-source-connector\node_modules\sparqljs\lib\SparqlGenerator.js:156:34)
    at Generator.toQuery (C:\Users\User\Documents\ontology-source-connector\node_modules\sparqljs\lib\SparqlGenerator.js:49:30)
    at Object.stringify (C:\Users\User\Documents\ontology-source-connector\node_modules\sparqljs\lib\SparqlGenerator.js:455:44)
    at toSparql (C:\Users\User\Documents\ontology-source-connector\node_modules\sparqlalgebrajs\lib\sparql.js:42:22)
    at ActorQueryOperationSparqlEndpoint.run (C:\Users\User\Documents\ontology-source-connector\node_modules\@comunica\actor-query-operation-sparql-endpoint\lib\ActorQueryOperationSparqlEndpoint.js:76:52)
```

Querying the graphDB SPARQL endpoint with SELECT works perfectly fine. Updating with INSERT DATA or DELETE DATA does not. I had a look into respective code throwing the error. I found out, that the problem can be solved by including all prefixes in the update query. When using an update query, it seems as if basic namespaces (xsd, rdf, rdfs, owl) do not seem to be automatically inserted, which is why, in the end, the update query gets wrapped in a select query and subsequently errors. When using SELECT instead, common prefixes (rdf, rdfs, ...) are automatically being inserted, if missing in the query.

Note: I edited this post several times due to further investigation and insights in the process. Now, I am quite sure, that this bug seems to be related or possibly is the same as here: https://github.com/comunica/comunica/issues/1251

____
#### Environment:

| software          | version
| ---------------- | -------
| Comunica Engine  | 2.9.0
| node             | v18.17.1
| npm              | 9.6.7
| yarn             | _Yarn is unavailable_
| Operating System | win32 (Windows_NT 10.0.22621)

**Comment by rubensworks** [comment]
FYI, we're working on Comunica v3, which will focus on improving performance of federated querying across SPARQL endpoints. This should resolve this issue when completed.
