### ISSUE TITLE
Negated property paths crash during parsing

### ISSUE THREAD

**Issue by rubensworks** [comunica/comunica#218]
#### Issue type:

- :bug: Bug

____
#### Description:

Executing `http://fragments.dbpedia.org/2015-10/en "SELECT * WHERE { <http://dbpedia.org/resource/12_Monkeys> !<http://dbpedia.org/ontology/starring> ?o } LIMIT 100"` crashes during the parsing phase.

I assume there is something going wrong in sparqlalgebrajs, but it's not immediately clear to me what exactly, so let's track this issue here until we pinpoint the cause.

____

#### Crash log:

```
TypeError: items is not iterable
    at translatePathPredicate (/Users/rtaelman/Documents/UGent/nosync/comunica/node_modules/sparqlalgebrajs/lib/sparqlAlgebra.js:192:26)
    at translatePath (/Users/rtaelman/Documents/UGent/nosync/comunica/node_modules/sparqlalgebrajs/lib/sparqlAlgebra.js:178:16)
    at translateBgp (/Users/rtaelman/Documents/UGent/nosync/comunica/node_modules/sparqlalgebrajs/lib/sparqlAlgebra.js:155:24)
    at translateGroupGraphPattern (/Users/rtaelman/Documents/UGent/nosync/comunica/node_modules/sparqlalgebrajs/lib/sparqlAlgebra.js:104:16)
    at accumulateGroupGraphPattern (/Users/rtaelman/Documents/UGent/nosync/comunica/node_modules/sparqlalgebrajs/lib/sparqlAlgebra.js:298:17)
    at Array.reduce (<anonymous>)
    at translateGroupGraphPattern (/Users/rtaelman/Documents/UGent/nosync/comunica/node_modules/sparqlalgebrajs/lib/sparqlAlgebra.js:118:29)
    at translateQuery (/Users/rtaelman/Documents/UGent/nosync/comunica/node_modules/sparqlalgebrajs/lib/sparqlAlgebra.js:44:15)
    at Object.translate (/Users/rtaelman/Documents/UGent/nosync/comunica/node_modules/sparqlalgebrajs/lib/sparqlAlgebra.js:32:12)
    at ActorSparqlParseAlgebra.run (/Users/rtaelman/Documents/UGent/nosync/comunica/node_modules/@comunica/actor-sparql-parse-algebra/lib/ActorSparqlParseAlgebra.js:19:47)
```

**Comment by joachimvh** [comment]
Fixed in bb5b837210a5851f4cd586ac993a8c3b8fb3d9aa by updating to sparqlalgebra.js v1.1.0
