### ISSUE TITLE
Docker run not working

### ISSUE THREAD

**Issue by bjdmeest** [comunica/comunica#334]
#### Issue type:

- :bug: Bug

____
#### Description:

Running `docker run comunica/actor-init-sparql http://fragments.dbpedia.org/2015-10/en "CONSTRUCT WHERE { ?s ?p ?o } LIMIT 100"` gives an error:

```
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module '@comunica/actor-init-sparql'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/var/www/@comunica/actor-init-sparql/engine-default.js:540:38)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
```
____

**Comment by rubensworks** [comment]
Ok, this was a Components.js issue, will publish a new release in a bit.

**Comment by rubensworks** [comment]
Latest and 1.4.4 should work properly now.
