### ISSUE TITLE
Some errors are not being caught properly

### ISSUE THREAD

**Issue by rubensworks** [comunica/comunica#381]
#### Issue type:

- :bug: Bug

____
#### Description:

Some errors, like HTTP 404's, are not being emitted properly to the caller.

For example, the following code snippet will not be able to catch the 404 error that originates from the given source:
```javascript
myEngine.query(query,
  { sources: [ { type: 'hypermedia', value: 'http://rubensworksssssssss.net/' } ] })
  .then(function (result) {
    result.bindingsStream.on('data', console.log);
    result.bindingsStream.on('error', () => console.error('a'));
  }).catch(() => console.error('b'));
```

Instead, we get the following output:
```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND rubensworksssssssss.net rubensworksssssssss.net:80
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
Emitted 'error' event at:
    at ClientRequest.eventHandlers.(anonymous function) (/Users/rtaelman/Documents/UGent/nosync/comunica/node_modules/follow-redirects/index.js:17:24)
    at ClientRequest.emit (events.js:182:13)
    at Socket.socketErrorListener (_http_client.js:392:9)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by RubenVerborgh** [comment]
Can we prioritize this one for LDflex?

**Comment by rubensworks** [comment]
I'll try to make some time for this tomorrow.
