### ISSUE TITLE
UnhandledPromiseRejections in tests

### ISSUE THREAD

**Issue by michielbdejong** [comunica/comunica#568]
#### Issue type:

_Only keep the issue types that are applicable._

- :bug: Bug

#### Description:

When running the tests, I see the following errors scroll by:
```sh

ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.

      at SparqlEndpointFetcher.<anonymous> (node_modules/fetch-sparql-endpoint/lib/SparqlEndpointFetcher.js:117:36)
      at fulfilled (node_modules/fetch-sparql-endpoint/lib/SparqlEndpointFetcher.js:4:58)
(node:16513) UnhandledPromiseRejectionWarning: TypeError: require(...) is not a function
(node:16513) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:16513) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

```sh
(node:16517) UnhandledPromiseRejectionWarning: Error: actor sparql serialize tree test error
(node:16517) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 36)
(node:16517) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
____
#### Environment:

_Exact versions of the software in your environment, not just *latest*. Only needed for :bug: and :snail:._

| software            | version(s)
| ------------------- | -------
| Comunica Init Actor | latest master
| Comunica            | latest master
| node                | v12.7.0
| npm                 | 6.10.0
| yarn                | 1.15.2
| Operating System    | Mac OSX

**Comment by michielbdejong** [comment]
Traced one of them down to:
```sh
./node_modules/.bin/jest packages/actor-sparql-serialize-tree/test/ActorSparqlSerializeTree-test.ts 
(node:16712) UnhandledPromiseRejectionWarning: Error: actor sparql serialize tree test error
(node:16712) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:16712) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 PASS  packages/actor-sparql-serialize-tree/test/ActorSparqlSerializeTree-test.ts
```
Possibly related to #565?

**Comment by michielbdejong** [comment]
The "You are trying to `import`" one seems to be in:
```sh
$ ./node_modules/.bin/jest packages/actor-init-sparql/test/
 PASS  packages/actor-init-sparql/test/ActorInitSparql-test.ts
 PASS  packages/actor-init-sparql/test/HttpServiceSparqlEndpoint-test.ts

ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.

      at SparqlEndpointFetcher.<anonymous> (node_modules/fetch-sparql-endpoint/lib/SparqlEndpointFetcher.js:117:36)
      at fulfilled (node_modules/fetch-sparql-endpoint/lib/SparqlEndpointFetcher.js:4:58)
(node:18012) UnhandledPromiseRejectionWarning: TypeError: require(...) is not a function
(node:18012) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:18012) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 PASS  packages/actor-init-sparql/test/index-test.ts
 PASS  packages/actor-init-sparql/test/QueryDynamic-test.ts (7.77s)
```
and this one hangs when you run it alone:
```sh
./node_modules/.bin/jest packages/actor-init-sparql/test/HttpServiceSparqlEndpoint-test.ts --detectOpenHandles
```

**Comment by rubensworks** [comment]
Thanks for opening an issue on this. I also saw these errors sneaking in lately, but I haven't found the time yet to look into fixing them.

My guess is that most of them are caused by missing `await`'s in tests.

**Comment by michielbdejong** [comment]
https://github.com/comunica/comunica/pull/567#issuecomment-552797274 should help, maybe
