### ISSUE TITLE
GraphQL-LD example crashe

### ISSUE THREAD

**Issue by ofilangi** [comunica/comunica#626]
#### Issue type:

- :bug: Bug

____
#### Description:

The Readme [GraphQL-LD example](https://github.com/comunica/comunica/tree/master/packages/actor-init-sparql#optional-graphql-ld) does not work  

____
#### Environment:

```
| software            | version
| ------------------- | -------
| Comunica Init Actor | 1.10.0 
| node                | v13.9.0
| npm                 | 6.13.7
| yarn                | _Yarn is unavailable_
| Operating System    | linux (Linux 4.4.0-21-generic)

```

#### Crash log:
```
(node:11616) UnhandledPromiseRejectionWarning: Error: Missing @id in context entry: 'artist_label': '{"@singular":true}'
    at Function.validate (/home/xxx/workspace/sparql_js/communica_test/node_modules/jsonld-context-parser/lib/ContextParser.js:331:35)
    at ContextParser.<anonymous> (/home/xxx/workspace/sparql_js/communica_test/node_modules/jsonld-context-parser/lib/ContextParser.js:454:35)
    at Generator.next (<anonymous>)
    at /home/xxx/workspace/sparql_js/communica_test/node_modules/jsonld-context-parser/lib/ContextParser.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/xxx/workspace/sparql_js/communica_test/node_modules/jsonld-context-parser/lib/ContextParser.js:3:12)
    at ContextParser.parse (/home/xxx/workspace/sparql_js/communica_test/node_modules/jsonld-context-parser/lib/ContextParser.js:401:16)
    at Converter.<anonymous> (/home/xx/workspace/sparql_js/communica_test/node_modules/graphql-to-sparql/lib/Converter.js:62:102)
    at Generator.next (<anonymous>)
    at /home/xxx/workspace/sparql_js/communica_test/node_modules/graphql-to-sparql/lib/Converter.js:7:71
(node:11616) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:11616) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by rubensworks** [comment]
Thanks for reporting, that part of the README seems to be outdated. Will fix it right away!
