### ISSUE TITLE
RDF dereference fails on some IRIs

### ISSUE THREAD

**Issue by ddeboer** [comunica/comunica#775]
#### Issue type:

- :bug: Bug 

____
#### Description:

RDF dereference fails on some IRIs, such as https://data.bibliotheken.nl/doc/dataset/rise-alba, while a cURL works fine:

```
curl -H Accept:text/turtle https://data.bibliotheken.nl/doc/dataset/rise-alba -v
...
< HTTP/1.1 200 OK
...
<id/dataset/rise-alba>
        a                             schema:Dataset ;
...
```
____
#### Environment:

```
comunica-sparql https://data.bibliotheken.nl/doc/dataset/rise-alba -q 'SELECT * WHERE { ?s ?p ?p }'
[Could not retrieve https://data.bibliotheken.nl/doc/dataset/rise-alba (500: unknown error)
```

#### Crash log:

```
Error: Could not retrieve https://data.bibliotheken.nl/doc/dataset/rise-alba (500: unknown error)
    at ActorRdfDereferenceHttpParse.run (/Users/david/src/netwerk-digitaal-erfgoed/registry-api/node_modules/@comunica/actor-rdf-dereference-http-parse/lib/ActorRdfDereferenceHttpParseBase.js:56:27)
    at dereference (/Users/david/src/netwerk-digitaal-erfgoed/registry-api/src/fetch.ts:28:20)
    at validate (/Users/david/src/netwerk-digitaal-erfgoed/registry-api/src/server.ts:35:15)
    at Object.<anonymous> (/Users/david/src/netwerk-digitaal-erfgoed/registry-api/src/server.ts:76:8)
```

**Comment by rubensworks** [comment]
This looks like a server configuration error.

Comunica uses a slightly more complex accept header:
```
$ curl -H "Accept: application/n-quads,application/trig;q=0.95,application/ld+json;q=0.9,application/n-triples;q=0.8,text/turtle;q=0.6,application/rdf+xml;q=0.5,application/jso5,text/n3;q=0.35,application/xml;q=0.3,text/xml;q=0.3,image/svg+xml;q=0.3,text/html;q=0.2,application/xhtml+xml;q=0.18" https://data.bibliotheken.nl/doc/dataset/rise-alba -v
```

Performing this request via curl results in the same server error, even though the accept header is valid.

(For future reference, the accept header that Comunica sends can be observed by enabling the logger: `-l debug`, after #774 is fixed that is)

**Comment by ddeboer** [comment]
Definitely looks like misconfigured content negotiation on the server. Thanks @rubensworks!
