### ISSUE TITLE
Error: Unexpected "" on line 1 when parsing Turtle response

### ISSUE THREAD

**Issue by ddeboer** [comunica/comunica#778]
#### Issue type:

- :bug: Bug 

____
#### Description:

```
comunica-sparql https://littest.hosting.deventit.net/Atlantispubliek/data/set/catalog.ttl  "SELECT * WHERE { ?s ?p ?o }"
[events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: Unexpected "" on line 1.
    at N3Lexer._syntaxError (/usr/local/lib/node_modules/@comunica/actor-init-sparql/node_modules/n3/lib/N3Lexer.js:466:17)
```

```
curl  -vv  -H "Accept:application/n-quads,application/trig;q=0.95,application/ld+json;q=0.9,application/n-triples;q=0.8,text/turtle;q=0.6,application/rdf+xml;q=0.5,application/json;q=0.45,text/n3;q=0.35,application/xml;q=0.3,text/xml;q=0.3,image/svg+xml;q=0.3,text/html;q=0.2,application/xhtml+xml;q=0.18"  https://littest.hosting.deventit.net/Atlantispubliek/data/set/catalog.ttl
…
< Content-Type: text/turtle
< Content-Disposition: attachment; filename=catalog.ttl

@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>.
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
@prefix xsd: <http://www.w3.org/2001/XMLSchema#>.
@prefix xml: <http://www.w3.org/XML/1998/namespace>.
@prefix schema: <http://schema.org/>.

_:autos22 schema:dataset <https://littest.hosting.deventit.net/AtlantisPubliek/data/dataset/LOD+Museale+Objecten>,
```

Content-Type looks fine, but should Comunica pick the N3 parser for Turtle responses?

Not sure if the Content-Disposition is a problem.
____
#### Environment:

| software            | version
| ------------------- | -------
| Comunica Init Actor | 1.19.2
| node                | v14.15.2
| npm                 | 7.4.0
| yarn                | 1.22.10
| Operating System    | darwin (Darwin 20.3.0)

#### Crash log:

```
[2021-02-04T16:21:28.173Z]  INFO: Requesting https://littest.hosting.deventit.net/Atlantispubliek/data/set/catalog.ttl {
  headers: {
    accept: 'application/n-quads,application/trig;q=0.95,application/ld+json;q=0.9,application/n-triples;q=0.8,text/turtle;q=0.6,application/rdf+xml;q=0.5,application/json;q=0.45,text/n3;q=0.35,application/xml;q=0.3,text/xml;q=0.3,image/svg+xml;q=0.3,text/html;q=0.2,application/xhtml+xml;q=0.18',
    'user-agent': 'Comunica/actor-http-native (Node.js v14.15.2; darwin)'
  },
  actor: 'https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql/^1.0.0/config/sets/http.json#myHttpFetcher'
}
[events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: Unexpected "" on line 1.
    at N3Lexer._syntaxError (/usr/local/lib/node_modules/@comunica/actor-init-sparql/node_modules/n3/lib/N3Lexer.js:466:17)
    at reportSyntaxError (/usr/local/lib/node_modules/@comunica/actor-init-sparql/node_modules/n3/lib/N3Lexer.js:394:21)
    at N3Lexer._tokenizeToEnd (/usr/local/lib/node_modules/@comunica/actor-init-sparql/node_modules/n3/lib/N3Lexer.js:375:86)
    at /usr/local/lib/node_modules/@comunica/actor-init-sparql/node_modules/n3/lib/N3Lexer.js:515:22
    at N3StreamParser._transform (/usr/local/lib/node_modules/@comunica/actor-init-sparql/node_modules/n3/lib/N3StreamParser.js:46:7)
    at N3StreamParser.Transform._read (/usr/local/lib/node_modules/@comunica/actor-init-sparql/node_modules/readable-stream/lib/_stream_transform.js:177:10)
    at N3StreamParser.Transform._write (/usr/local/lib/node_modules/@comunica/actor-init-sparql/node_modules/readable-stream/lib/_stream_transform.js:164:83)
    at doWrite (/usr/local/lib/node_modules/@comunica/actor-init-sparql/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/usr/local/lib/node_modules/@comunica/actor-init-sparql/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at N3StreamParser.Writable.write (/usr/local/lib/node_modules/@comunica/actor-init-sparql/node_modules/readable-stream/lib/_stream_writable.js:307:11)
Emitted 'error' event on N3StreamParser instance at:
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at errorOrDestroy (internal/streams/destroy.js:168:7)
    at N3StreamParser.onerror (internal/streams/readable.js:758:9)
    at N3StreamParser.emit (events.js:315:20)
    at N3Parser._callback (/usr/local/lib/node_modules/@comunica/actor-init-sparql/node_modules/n3/lib/N3StreamParser.js:39:21)
    at /usr/local/lib/node_modules/@comunica/actor-init-sparql/node_modules/n3/lib/N3Parser.js:1073:32
    at reportSyntaxError (/usr/local/lib/node_modules/@comunica/actor-init-sparql/node_modules/n3/lib/N3Lexer.js:394:7)
    at N3Lexer._tokenizeToEnd (/usr/local/lib/node_modules/@comunica/actor-init-sparql/node_modules/n3/lib/N3Lexer.js:375:86)
    at /usr/local/lib/node_modules/@comunica/actor-init-sparql/node_modules/n3/lib/N3Lexer.js:515:22
    at N3StreamParser._transform (/usr/local/lib/node_modules/@comunica/actor-init-sparql/node_modules/n3/lib/N3StreamParser.js:46:7) {
  context: { token: undefined, line: 1, previousToken: undefined }
}
```

**Comment by rubensworks** [comment]
The file seems to have a byte order mark, which I suspect is not allowed in Turtle.
I'm not 100% sure though, can you confirm @RubenVerborgh?

**Comment by ddeboer** [comment]
Correct, it’s a UTF-8 file with a BOM. While [not recommended](https://www.unicode.org/versions/Unicode5.0.0/ch02.pdf (p. 36)) (p. 36), they are allowed in general. Not sure about Turtle specifically.

**Comment by RubenVerborgh** [comment]
Can't find any info, apart from SERD supporting it: https://www.drobilla.net/category/serd/index2.html
Shall we ask on the mailing list, or just roll with it?

**Comment by rubensworks** [comment]
I don't see any downsides to supporting it, but you may know better implementation-wise. But I guess we can roll with it :-)

**Comment by RubenVerborgh** [comment]
Following up in https://github.com/rdfjs/N3.js/issues/242

**Comment by rubensworks** [comment]
Should be fixed soon in https://github.com/rdfjs/N3.js/pull/258
