### ISSUE TITLE
Unexpected "\n" at position x in state STOP

### ISSUE THREAD

**Issue by coret** [comunica/comunica#785]
Using the current version of comunica-sparql a query on https://data.stad.gent/explore/dataset/vondelingen/information/ (which contains a valid dataset description) generates an error:

```
# comunica-sparql https://data.stad.gent/explore/dataset/vondelingen/information/  "SELECT * WHERE { ?s ?p ?o }"

[(node:20605) UnhandledPromiseRejectionWarning: Error: Unexpected "\n" at position 193 in state STOP
    at Function.newErrorCoded (/usr/local/lib/node_modules/@comunica/actor-init-sparql/node_modules/@comunica/actor-rdf-parse-html-script/lib/HtmlScriptListener.js:33:23)
    at JsonLdParser.<anonymous> (/usr/local/lib/node_modules/@comunica/actor-init-sparql/node_modules/@comunica/actor-rdf-parse-html-script/lib/HtmlScriptListener.js:86:26)
    at JsonLdParser.emit (events.js:327:22)
    at Parser.jsonParser.onError (/usr/local/lib/node_modules/@comunica/actor-init-sparql/node_modules/jsonld-streaming-parser/lib/JsonLdParser.js:370:18)
    at Parser.proto.charError (/usr/local/lib/node_modules/@comunica/actor-init-sparql/node_modules/jsonparse/jsonparse.js:90:8)
    at Parser.proto.write (/usr/local/lib/node_modules/@comunica/actor-init-sparql/node_modules/jsonparse/jsonparse.js:199:23)
    at JsonLdParser._transform (/usr/local/lib/node_modules/@comunica/actor-init-sparql/node_modules/jsonld-streaming-parser/lib/JsonLdParser.js:110:25)
    at JsonLdParser.Transform._read (internal/streams/transform.js:205:10)
    at JsonLdParser.Transform._write (internal/streams/transform.js:193:12)
    at doWrite (internal/streams/writable.js:377:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:20605) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 27)
(node:20605) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

See https://github.com/netwerk-digitaal-erfgoed/register/issues/69 which suggests Comunica might be tripping over the ogp properties?

**Comment by rubensworks** [comment]
This error indicates that the given document contains invalid JSON-LD.

When checking the source of https://data.stad.gent/explore/dataset/vondelingen/information/, this indeed seems to be true.
See for example the newlines in the JSON string starting on line 844. (JSON requires newlines in strings to be escaped)

**Comment by coret** [comment]
Thanks, I will contact data.stad.gent about this issue.

FYI: I was "mislead" by Google on the validity of JSON: both Google Structured Data Tool and Rich Results Test ignore the invalid newlines. https://jsonlint.com/ is a better first check.

**Comment by rubensworks** [comment]
> both Google Structured Data Tool and Rich Results Test ignore the invalid newlines

Oh, I didn't know that.
It's a bit unfortunate that they do this, deviating from the spec like this is bound to cause confusion (as proven by this issue).
