### ISSUE TITLE
Wrong Accepted header querying virtuoso

### ISSUE THREAD

**Issue by ccolonna** [comunica/comunica#833]
#### Issue type:

- :bug: Bug 

____
#### Description:

My comunica version is:

```
"@comunica/actor-init-sparql": "^1.19.2"
```

Querying [https://github.com/tenforce/docker-virtuoso](virtuoso) sparql endpoint with comunica i received this error.

```
Error: Invalid SPARQL endpoint (http://localhost:8890/sparql) response: undefined
```
The query is a simple ```SELECT * WHERE {?s ?p ?o}.```

Querying dbpedia works.

After further inspection i found problem is related to a subdependency of comunica, namely:

[https://www.npmjs.com/package/fetch-sparql-endpoint](fetch-sparql-endpoint)

In an older project, I had the same version of comunica. But that version has an older subdependecy of the above package, and the same query works.

Specifically:

crashing environment:

```
"@comunica/actor-init-sparql": "^1.19.2"
   | -- "fetch-sparql-endpoint": "^2.0.0"

```

working environment:

```
"@comunica/actor-init-sparql": "^1.19.2"
   | -- "fetch-sparql-endpoint": "^1.7.0"

```

Has I don't have control to comunica dependency I temporarily downgrade the version of ```fetch-sparql-endpoint``` with ```https://www.npmjs.com/package/npm-force-resolutions``` 

and solved the issue. Now I can query correctly. But i should rely on a third party resolution manager.

I added a log inside  ```fetch-sparql-endpoint``` package and print the failing http response from virtuoso. Down I provide the output. You can see is a `406` status code.

____
#### Crash log:

Error raised by ```fetch-sparql-endpoint```

```
      [!] SparqlClient.sendRequest error: Error: Invalid SPARQL endpoint (http://localhost:8890/sparql) response: undefined
          at SparqlEndpointFetcher.handleFetchCall (/home/colin/DevWorkspace/odp-reactor/odp-reactor-persistence-interface/node_modules/@comunica/actor-query-operation-sparql-endpoint/node_modules/fetch-sparql-endpoint/lib/SparqlEndpointFetcher.js:185:19)
          at SparqlEndpointFetcher.fetchBindings (/home/colin/DevWorkspace/odp-reactor/odp-reactor-persistence-interface/node_modules/@comunica/actor-query-operation-sparql-endpoint/node_modules/fetch-sparql-endpoint/lib/SparqlEndpointFetcher.js:83:47)
```

Logged HttpResponse received by comunica client from virtuoso: 

```
      {
        body: <ref *1> IncomingMessage {
          _readableState: ReadableState {
            objectMode: false,
            highWaterMark: 16384,
            buffer: BufferList { head: [Object], tail: [Object], length: 1 },
            length: 362,
            pipes: [],
            flowing: null,
            ended: true,
            endEmitted: false,
            reading: false,
            constructed: true,
            sync: true,
            needReadable: false,
            emittedReadable: false,
            readableListening: false,
            resumeScheduled: false,
            errorEmitted: false,
            emitClose: true,
            autoDestroy: true,
            destroyed: false,
            errored: null,
            closed: false,
            closeEmitted: false,
            defaultEncoding: 'utf8',
            awaitDrainWriters: null,
            multiAwaitDrain: false,
            readingMore: true,
            decoder: [StringDecoder],
            encoding: 'utf8',
            [Symbol(kPaused)]: null
          },
          _events: [Object: null prototype] {
            end: [Function: responseOnEnd],
            error: [Function (anonymous)]
          },
          _eventsCount: 2,
          _maxListeners: undefined,
          socket: Socket {
            connecting: false,
            _hadError: false,
            _parent: null,
            _host: 'localhost',
            _readableState: [ReadableState],
            _events: [Object: null prototype],
            _eventsCount: 6,
            _maxListeners: undefined,
            _writableState: [WritableState],
            allowHalfOpen: false,
            _sockname: null,
            _pendingData: null,
            _pendingEncoding: '',
            server: null,
            _server: null,
            parser: null,
            _httpMessage: [ClientRequest],
            [Symbol(async_id_symbol)]: 53,
            [Symbol(kHandle)]: [TCP],
            [Symbol(kSetNoDelay)]: false,
            [Symbol(lastWriteQueueSize)]: 0,
            [Symbol(timeout)]: null,
            [Symbol(kBuffer)]: null,
            [Symbol(kBufferCb)]: null,
            [Symbol(kBufferGen)]: null,
            [Symbol(kCapture)]: false,
            [Symbol(kBytesRead)]: 0,
            [Symbol(kBytesWritten)]: 0,
            [Symbol(RequestTimeout)]: undefined
          },
          httpVersionMajor: 1,
          httpVersionMinor: 1,
          httpVersion: '1.1',
          complete: true,
          rawHeaders: [
            'Server',
            'Virtuoso/07.20.3229 (Linux) x86_64-pc-linux-gnu',
            'Connection',
            'Keep-Alive',
            'Content-Type',
            'text/html; charset=UTF-8',
            'Date',
            'Fri, 25 Jun 2021 08:14:58 GMT',
            'Accept-Ranges',
            'bytes',
            'Alternates',
            '{"sparql" 1 {type text/html} {charset UTF-8} {length 12397}}',
            'Content-Length',
            '362'
          ],
          rawTrailers: [],
          aborted: false,
          upgrade: false,
          url: '',
          method: null,
          statusCode: 406,
          statusMessage: 'Unacceptable',
          client: Socket {
            connecting: false,
            _hadError: false,
            _parent: null,
            _host: 'localhost',
            _readableState: [ReadableState],
            _events: [Object: null prototype],
            _eventsCount: 6,
            _maxListeners: undefined,
            _writableState: [WritableState],
            allowHalfOpen: false,
            _sockname: null,
            _pendingData: null,
            _pendingEncoding: '',
            server: null,
            _server: null,
            parser: null,
            _httpMessage: [ClientRequest],
            [Symbol(async_id_symbol)]: 53,
            [Symbol(kHandle)]: [TCP],
            [Symbol(kSetNoDelay)]: false,
            [Symbol(lastWriteQueueSize)]: 0,
            [Symbol(timeout)]: null,
            [Symbol(kBuffer)]: null,
            [Symbol(kBufferCb)]: null,
            [Symbol(kBufferGen)]: null,
            [Symbol(kCapture)]: false,
            [Symbol(kBytesRead)]: 0,
            [Symbol(kBytesWritten)]: 0,
            [Symbol(RequestTimeout)]: undefined
          },
          _consuming: false,
          _dumped: false,
          req: ClientRequest {
            _events: [Object: null prototype],
            _eventsCount: 7,
            _maxListeners: undefined,
            outputData: [],
            outputSize: 0,
            writable: true,
            destroyed: false,
            _last: false,
            chunkedEncoding: true,
            shouldKeepAlive: true,
            _defaultKeepAlive: true,
            useChunkedEncodingByDefault: true,
            sendDate: false,
            _removedConnection: false,
            _removedContLen: false,
            _removedTE: false,
            _contentLength: null,
            _hasBody: true,
            _trailer: '',
            finished: true,
            _headerSent: true,
            _closed: false,
            socket: [Socket],
            _header: 'POST /sparql HTTP/1.1\r\n' +
              'accept: application/sparql-results+json;q=1.0,application/sparql-results+xml;q=0.7\r\n' +
              'content-type: application/x-www-form-urlencoded\r\n' +
              'user-agent: Comunica/actor-http-native (Node.js v16.1.0; linux)\r\n' +
              'Host: localhost:8890\r\n' +
              'Connection: keep-alive\r\n' +
              'Transfer-Encoding: chunked\r\n' +
              '\r\n',
            _keepAliveTimeout: 0,
            _onPendingData: [Function: nop],
            agent: [Agent],
            socketPath: undefined,
            method: 'POST',
            maxHeaderSize: undefined,
            insecureHTTPParser: undefined,
            path: '/sparql',
            _ended: false,
            res: [Circular *1],
            aborted: false,
            timeoutCb: null,
            upgradeOrConnect: false,
            parser: null,
            maxHeadersCount: null,
            reusedSocket: false,
            host: 'localhost',
            protocol: 'http:',
            _redirectable: [Writable],
            [Symbol(kCapture)]: false,
            [Symbol(kNeedDrain)]: false,
            [Symbol(corked)]: 0,
            [Symbol(kOutHeaders)]: [Object: null prototype]
          },
          responseUrl: 'http://localhost:8890/sparql',
          redirects: [],
          cancel: [Function (anonymous)],
          [Symbol(kCapture)]: false,
          [Symbol(kHeaders)]: Headers { [Symbol(map)]: [Object: null prototype] },
          [Symbol(kHeadersCount)]: 14,
          [Symbol(kTrailers)]: null,
          [Symbol(kTrailersCount)]: 0,
          [Symbol(RequestTimeout)]: undefined
        },
        headers: Headers {
          [Symbol(map)]: [Object: null prototype] {
            server: [Array],
            connection: [Array],
            'content-type': [Array],
            date: [Array],
            'accept-ranges': [Array],
            alternates: [Array],
            'content-length': [Array]
          }
        },
        ok: false,
        redirected: false,
        status: 406,
        url: 'http://localhost:8890/sparql'
      }
```

**Comment by rubensworks** [comment]
fetch-sparql-endpoint now uses POST-based SPARQL requests to endpoints, which is usually better. (and spec-compliant)

Probably means that https://github.com/tenforce/docker-virtuoso uses an outdated version of Virtuoso that contains some bug regarding POST-based requests, while the public virtuoso endpoint for dbpedia uses a more recent version that had the bug fixed already.

What may work, is forcing the source type to `sparql` (see docs).

If that doesn't work, disabling this option in a custom config should do the trick: https://github.com/comunica/comunica/blob/master/packages/actor-query-operation-sparql-endpoint/components/Actor/QueryOperation/SparqlEndpoint.jsonld#L23

The best solution would be to use a more up-to-date version if virtuoso, but in the meantime I'll leave this issue open to see if someone can figure out a solution that would make things work more broadly.

**Comment by ccolonna** [comment]
Thanks @rubensworks  for answering. 

> What may work, is forcing the source type to `sparql` (see docs).

already did this but didn't work.

> If that doesn't work, disabling this option in a custom config should do the trick: https://github.com/comunica/comunica/blob/master/packages/actor-query-operation-sparql-endpoint/components/Actor/QueryOperation/SparqlEndpoint.jsonld#L23

This solution is not that suitable as I would need to handle a custom comunica fork or something like that and meanwhile sync to master.  

> The best solution would be to use a more up-to-date version if virtuoso, but in the meantime I'll leave this issue open to see if someone can figure out a solution that would make things work more broadly.

Unfortunately as far as i know the only dockerized virtuoso image has latest update on 2018.

Anyway I easily adopted this workaround:



(1) install ```npm-force-resolutions``` as a dev dependency:

``` $ npm install npm-force-resolutions --save-dev```

(2)  install version 1.9 of ```fetch-sparql-endpoint```:

``` $ npm install fetch-sparql-endpoint@1.9.0```

(3) add this key to you're ```package.json``` file:

```
  "resolutions": {
    "fetch-sparql-endpoint": "1.9.0"
  }
```

(4) add this to the scripts section of ```package.json```:

```
  "scripts": {
    ...
    "preinstall": "npx npm-force-resolutions",
  }
```

(5) run ```npm install```

If can help anyone this is my one.

**Comment by rubensworks** [comment]
> This solution is not that suitable as I would need to handle a custom comunica fork or something like that and meanwhile sync to master.

A fork should not be necessary.
Could just be achieved like this: https://comunica.dev/docs/modify/getting_started/custom_config_app/

> Unfortunately as far as i know the only dockerized virtuoso image has latest update on 2018.

3 years is a long time in the software world.
Perhaps the official Virtuoso container works better? (updated 6 days ago): https://hub.docker.com/r/openlink/virtuoso-opensource-7

> (2) install version 1.9 of fetch-sparql-endpoint:

Good that this works, but definitely not recommended :-)

**Comment by ccolonna** [comment]
> Could just be achieved like this: https://comunica.dev/docs/modify/getting_started/custom_config_app/

Nice to know of this

> Perhaps the official Virtuoso container works better? (updated 6 days ago): https://hub.docker.com/r/openlink/virtuoso-opensource-7

definitevely better!

It works now ;)

**Comment by rubensworks** [comment]
Ah, that's great to hear :-)

Closing this issue then.

Should anyone else run into this, please comment here.
