### ISSUE TITLE
Unhandled parse error

### ISSUE THREAD

**Issue by ddeboer** [comunica/comunica#872]
#### Issue type:

- :bug: Bug 

____
#### Description:

When querying invalid Turtle, Comunica crashes with an unhandled error. For example:

```
comunica-sparql https://lab.coret.org/register/kb-dates-invalid.ttl "SELECT * WHERE { ?s ?p ?o}"
```

Let me know if I should report this issue in N3.js instead.

____
#### Environment:

| software            | version
| ------------------- | -------
| Comunica Init Actor | 1.22.3
| node                | v14.17.6
| npm                 | 6.14.15
| yarn                | _Yarn is unavailable_
| Operating System    | darwin (Darwin 20.6.0)

#### Crash log:

<details>
  Crash log
  <summary>Crash log</summary>

```
[events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: Expected entity but got abbreviation on line 18.
    at N3Parser._error (/usr/local/lib/node_modules/@comunica/actor-init-sparql/node_modules/n3/lib/N3Parser.js:924:17)
    at N3Parser._readEntity (/usr/local/lib/node_modules/@comunica/actor-init-sparql/node_modules/n3/lib/N3Parser.js:200:21)
    at N3Parser._readObject (/usr/local/lib/node_modules/@comunica/actor-init-sparql/node_modules/n3/lib/N3Parser.js:361:34)
    at /usr/local/lib/node_modules/@comunica/actor-init-sparql/node_modules/n3/lib/N3Parser.js:1073:127
    at N3Lexer._tokenizeToEnd (/usr/local/lib/node_modules/@comunica/actor-init-sparql/node_modules/n3/lib/N3Lexer.js:385:7)
    at /usr/local/lib/node_modules/@comunica/actor-init-sparql/node_modules/n3/lib/N3Lexer.js:520:22
    at N3StreamParser._transform (/usr/local/lib/node_modules/@comunica/actor-init-sparql/node_modules/n3/lib/N3StreamParser.js:46:7)
    at N3StreamParser.Transform._read (/usr/local/lib/node_modules/@comunica/actor-init-sparql/node_modules/readable-stream/lib/_stream_transform.js:177:10)
    at N3StreamParser.Transform._write (/usr/local/lib/node_modules/@comunica/actor-init-sparql/node_modules/readable-stream/lib/_stream_transform.js:164:83)
    at doWrite (/usr/local/lib/node_modules/@comunica/actor-init-sparql/node_modules/readable-stream/lib/_stream_writable.js:409:139)
Emitted 'error' event on N3StreamParser instance at:
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at errorOrDestroy (internal/streams/destroy.js:168:7)
    at N3StreamParser.onerror (internal/streams/readable.js:743:9)
    at N3StreamParser.emit (events.js:400:28)
    at N3Parser._callback (/usr/local/lib/node_modules/@comunica/actor-init-sparql/node_modules/n3/lib/N3StreamParser.js:39:21)
    at N3Parser._error (/usr/local/lib/node_modules/@comunica/actor-init-sparql/node_modules/n3/lib/N3Parser.js:931:10)
    at N3Parser._readEntity (/usr/local/lib/node_modules/@comunica/actor-init-sparql/node_modules/n3/lib/N3Parser.js:200:21)
    [... lines matching original stack trace ...]
    at N3Lexer._tokenizeToEnd (/usr/local/lib/node_modules/@comunica/actor-init-sparql/node_modules/n3/lib/N3Lexer.js:385:7) {
  context: {
    token: { line: 18, type: 'abbreviation', value: 'a', prefix: '' },
    line: 18,
    previousToken: { line: 17, type: 'IRI', value: 'https://www.kb.nl/', prefix: '' }
  }
}
```
</summary>
</details>

**Comment by rubensworks** [comment]
Should be fixed in 2.0.5
