### ISSUE TITLE
Unbound variable from SPARQL endpoint when querying with initial bindings

### ISSUE THREAD

**Issue by ddeboer** [comunica/comunica#941]
#### Issue type:

- :bug: Bug 

____
#### Description:

With a simple Turtle file `test.ttl`:

```turtle
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

<https://example.com/resources/artwork>
    skos:prefLabel "Nachtwacht" .
```

Start a new SPARQL server:

```shell
$ comunica-sparql-file-http test.ttl
Server running on http://localhost:3000/sparql
Server worker (11515) running on http://localhost:3000/sparql
```

If you query it with an initial binding (`?var1`):

```typescript
    const quadStream = await new QueryEngine().queryQuads(
      'CONSTRUCT {?s ?p ?o } WHERE {?s ?p ?o . FILTER (?o = ?var1)}', {
        sources: ['http://localhost:3000/sparql'],
        initialBindings: new BindingsFactory().fromRecord({
          var1: new DataFactory().literal('Nachtwacht'),
        }),
      }
    );
    console.log(await quadStream.toArray());
```

Then the SPARQL server fails with:

```
[200] POST to /sparql
      Requested media type: text/turtle
      Received query query: CONSTRUCT {?s ?p ?o } WHERE {?s ?p ?o . FILTER (?o = ?var1)}
[2022-03-05T13:46:41.196Z]  WARN: Error occurred while filtering. {
  error: UnboundVariableError: Unbound variable '"?var1"' {"type":"bindings","dataFactory":{"blankNodeCounter":0,"blankNodePrefix":"df_965_"},"entries":{"s":{"termType":"NamedNode","value":"https://example.com/resources/artwork"},"p":{"termType":"NamedNode","value":"http://www.w3.org/2004/02/skos/core#prefLabel"},"o":{"termType":"Literal","value":"Nachtwacht","language":"","datatype":{"termType":"NamedNode","value":"http://www.w3.org/2001/XMLSchema#string"}}}}
      at AsyncRecursiveEvaluator.variable (/Users/david/src/netwerk-digitaal-erfgoed/network-of-terms/node_modules/sparqlee/dist/lib/evaluators/evaluatorHelpers/BaseExpressionEvaluator.js:16:19)
      at AsyncRecursiveEvaluator.evaluate (/Users/david/src/netwerk-digitaal-erfgoed/network-of-terms/node_modules/sparqlee/dist/lib/evaluators/evaluatorHelpers/AsyncRecursiveEvaluator.js:30:36)
      at /Users/david/src/netwerk-digitaal-erfgoed/network-of-terms/node_modules/sparqlee/dist/lib/evaluators/evaluatorHelpers/AsyncRecursiveEvaluator.js:33:55
      at Array.map (<anonymous>)
      at AsyncRecursiveEvaluator.evalOperator (/Users/david/src/netwerk-digitaal-erfgoed/network-of-terms/node_modules/sparqlee/dist/lib/evaluators/evaluatorHelpers/AsyncRecursiveEvaluator.js:33:39)
      at AsyncRecursiveEvaluator.evaluate (/Users/david/src/netwerk-digitaal-erfgoed/network-of-terms/node_modules/sparqlee/dist/lib/evaluators/evaluatorHelpers/AsyncRecursiveEvaluator.js:30:36)
      at AsyncEvaluator.evaluateAsEBV (/Users/david/src/netwerk-digitaal-erfgoed/network-of-terms/node_modules/sparqlee/dist/lib/evaluators/AsyncEvaluator.js:38:45)
      at SimpleTransformIterator.transform [as _transform] (/Users/david/src/netwerk-digitaal-erfgoed/network-of-terms/node_modules/@comunica/actor-query-operation-filter-sparqlee/lib/ActorQueryOperationFilterSparqlee.js:28:48)
      at SimpleTransformIterator._readAndTransformSimple (/Users/david/src/netwerk-digitaal-erfgoed/network-of-terms/node_modules/asynciterator/dist/asynciterator.cjs:1182:26)
      at SimpleTransformIterator._read (/Users/david/src/netwerk-digitaal-erfgoed/network-of-terms/node_modules/asynciterator/dist/asynciterator.cjs:1146:14) {
    variable: '?var1',
    bindings: Bindings {
      type: 'bindings',
      dataFactory: [DataFactory],
      entries: [Map]
    }
  },
  bindings: '{\n' +
    '  "s": "https://example.com/resources/artwork",\n' +
    '  "p": "http://www.w3.org/2004/02/skos/core#prefLabel",\n' +
    '  "o": "\\"Nachtwacht\\""\n' +
    '}',
  actor: 'urn:comunica:default:query-operation/actors#filter'
}
```

The same query works fine if it doesn’t use the initial binding (replace `?var1` with `Nachtwacht`):

```typescript
      'CONSTRUCT {?s ?p ?o } WHERE {?s ?p ?o . FILTER (?o = "Nachtwacht")}', {
```

The query with initial binding (`?var1`) also worked fine on Comunica < 2.0.
____
#### Environment:

| software         | version
| ---------------- | -------
| Comunica Engine  | 2.0.3
| node             | v16.14.0
| npm              | 8.3.1
| yarn             | _Yarn is unavailable_
| Operating System | darwin (Darwin 21.3.0)

**Comment by rubensworks** [comment]
Just looked into this a bit, and it looks like the initial bindings application works fine, but it only fails when trying to bind a variable within the `FILTER` clause.
@joachimvh could this be a recent regression in SPARQLAlgebra.js?

We probably want to add an integration test for that specific case in this repo.

**Comment by joachimvh** [comment]
Could be an issue caused by the recent change to check in scope variables, will have a look later.

**Comment by rubensworks** [comment]
@joachimvh I guess there are 2 ways to determine in-scope variables: one according to the SPARQL semantics, and one where you just list _all_ variables that occur in the query. For initial bindings application, we probably want that second one.

**Comment by joachimvh** [comment]
The algebra generated from `CONSTRUCT {?s ?p ?o } WHERE {?s ?p ?o . FILTER (?o = ?var1)}` is the same before or after the variable change, so I will need some more details on what exactly the issue is within Comunica. How are these initial bindings applied? Is the algebra changed to insert a values block, are all occurrences of `?var1` changed to the value, or something else? I would expect the first two to still work.

**Comment by rubensworks** [comment]
Thanks for checking @joachimvh. The initial bindings application actually works fine.
It's just the functionality that sends the original query string to the SPARQL endpoint that breaks things.
Fix incoming in a bit.

**Comment by ddeboer** [comment]
Thanks @rubensworks and @joachimvh for investigating and fixing this so quickly! This allowed us to upgrade to Comunica v2.

**Comment by rubensworks** [comment]
That's great to hear!
