### ISSUE TITLE
Random integration test failures

### ISSUE THREAD

**Issue by rubensworks** [comunica/comunica#975]
#### Issue type:

- :bug: Bug 

____
#### Description:

Random integration tests fail, possibly because fetch is happening after test has already ended.

Possibly related to https://github.com/comunica/comunica/commit/9ad64da7bae9dda857e12b7bb0b3af58d5f0f2af

____
#### Environment:

Latest master

#### Crash log:

```
FAIL engines/query-sparql/test/QuerySparql-test.ts (25.201 s)
  ● System test: QuerySparql › query › simple SPO on a TPF entrypoint › with filtered results

    Error [ERR_UNHANDLED_ERROR]: Unhandled error. (FetchError {
      message: 'request to https://fragments.dbpedia.org/2016-04/en?page=4 failed, reason: [Polly] [adapter:node-http] Unhandled request: \n' +
        '{\n' +
        '  "url": "https://fragments.dbpedia.org/2016-04/en?page=4",\n' +
        '  "method": "GET",\n' +
        '  "headers": {\n' +
        '    "accept": [\n' +
        '      "application/n-quads,application/trig;q=0.95,application/ld+json;q=0.9,application/n-triples;q=0.8,text/turtle;q=0.6,application/rdf+xml;q=0.5,application/json;q=0.45,text/n3;q=0.35,application/xml;q=0.3,image/svg+xml;q=0.3,text/xml;q=0.3,text/html;q=0.2,application/xhtml+xml;q=0.18"\n' +
        '    ],\n' +
        '    "user-agent": [\n' +
        '      "Comunica/actor-http-fetch (Node.js v14.19.1; linux)"\n' +
        '    ],\n' +
        '    "accept-encoding": [\n' +
        '      "gzip,deflate"\n' +
        '    ],\n' +
        '    "host": "fragments.dbpedia.org"\n' +
        '  },\n' +
        '  "body": "",\n' +
        '  "recordingName": "System test: QuerySparql/query/simple SPO on a TPF entrypoint/with results",\n' +
        '  "id": "188cf214193a599da2225504b780bc02",\n' +
        '  "order": 0,\n' +
        '  "identifiers": {\n' +
        '    "headers": {\n' +
        '      "accept": [\n' +
        '        "application/n-quads,application/trig;q=0.95,application/ld+json;q=0.9,application/n-triples;q=0.8,text/turtle;q=0.6,application/rdf+xml;q=0.5,application/json;q=0.45,text/n3;q=0.35,application/xml;q=0.3,image/svg+xml;q=0.3,text/xml;q=0.3,text/html;q=0.2,application/xhtml+xml;q=0.18"\n' +
        '      ],\n' +
        '      "accept-encoding": [\n' +
        '        "gzip,deflate"\n' +
        '      ],\n' +
        '      "host": "fragments.dbpedia.org"\n' +
        '    },\n' +
        '    "method": "GET",\n' +
        '    "url": "https://fragments.dbpedia.org/2016-04/en?page=4"\n' +
        '  },\n' +
        '  "config": {\n' +
        '    "mode": "stopped",\n' +
        '    "adapters": [\n' +
        '      null\n' +
        '    ],\n' +
        '    "logLevel": 3,\n' +
        '    "flushRequestsOnStop": false,\n' +
        '    "recordIfMissing": true,\n' +
        '    "recordFailedRequests": true,\n' +
        '    "expiresIn": null,\n' +
        '    "expiryStrategy": "warn",\n' +
        '    "matchRequestsBy": {\n' +
        '      "method": true,\n' +
        '      "headers": {\n' +
        '        "exclude": [\n' +
        '          "user-agent"\n' +
        '        ]\n' +
        '      },\n' +
        '      "body": true,\n' +
        '      "order": true,\n' +
        '      "url": {\n' +
        '        "protocol": true,\n' +
        '        "username": true,\n' +
        '        "password": true,\n' +
        '        "hostname": true,\n' +
        '        "port": true,\n' +
        '        "pathname": true,\n' +
        '        "query": true,\n' +
        '        "hash": false\n' +
        '      }\n' +
        '    }\n' +
        '  }\n' +
        '}',
      type: 'system',
      errno: undefined,
      code: undefined
    })

      235 |                 this.startIterator(nextSourceState, false);
      236 |               })
    > 237 |               .catch(error => this.destroy(error));
          |                                    ^
      238 |           } else {
      239 |             break;
      240 |           }

      at SimpleTransformIterator.destinationEmitError (node_modules/asynciterator/dist/asynciterator.cjs:1081:23)
      at MediatedLinkedRdfSourcesAsyncRdfIterator.destinationEmitError (node_modules/asynciterator/dist/asynciterator.cjs:1081:23)
      at node_modules/asynciterator/dist/asynciterator.cjs:177:26
      at MediatedLinkedRdfSourcesAsyncRdfIterator._destroy (node_modules/asynciterator/dist/asynciterator.cjs:892:9)
      at MediatedLinkedRdfSourcesAsyncRdfIterator.destroy (node_modules/asynciterator/dist/asynciterator.cjs:174:18)
      at packages/actor-rdf-resolve-quad-pattern-hypermedia/lib/LinkedRdfSourcesAsyncRdfIterator.ts:237:36
```

**Comment by rubensworks** [comment]
Duplicate of #947
